{
 "title": "Internet Gateway Watcher",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Online Status over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "igw_metric_status_info{instance=\"10.0.0.102:8001\", job=\"igw\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version und Build Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "igw_build_version_info" }
   ]
  },
  {
   "title": "Running Cycles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "igw_script_cycle_info{instance=\"10.0.0.102:8001\", job=\"igw\"}"
    }
   ]
  },
  {
   "title": "Ping Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igw_metric_ping_status{instance=\"10.0.0.102:8001\",job=\"igw\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InternetGatewayWatcher Infos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igw_metric_status_info{instance=\"10.0.0.102:8001\", job=\"igw\"}"
    }
   ]
  },
  {
   "title": "Latenz",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "igw_metric_ping_latenz{instance=\"10.0.0.102:8001\",job=\"igw\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "latest Latenz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igw_metric_ping_latenz{instance=\"10.0.0.102:8001\",job=\"igw\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline minutes last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (igw_metric_status_info{instance=\"10.0.0.102:8001\", job=\"igw\"}) * 10 / 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}